/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/ipod.gltf -o src/components/Ipod.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ipod(props) {
  const { nodes, materials } = useGLTF('/models/ipod.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/models/ipod.gltf')
